### ISSUE TITLE
Add `git` dependency

### ISSUE THREAD

**Issue by diegoferigo** [conda-forge/robot_descriptions-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Since `robot_descriptions` heavily relies on the `git` executable to clone the repos providing the robot models, is there any specific reason why `git` is not a run requirement?

xref https://github.com/conda-forge/rod-feedstock/pull/8#issuecomment-2120343587

cc @GiulioRomualdi @stephane-caron 

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by stephane-caron** [comment]
Thanks for raising this point. The `git` executable is a requirement of GitPython as indicated in [its readme](https://github.com/gitpython-developers/GitPython?tab=readme-ov-file#requirements), and I don't see a corresponding `requirement` in the [gitpython conda-forge recipe](https://github.com/conda-forge/gitpython-feedstock/blob/7eafcb6a08ecfc216fbd0bd4319a88b66d2901db/recipe/meta.yaml) (I see that you have [also checked](https://github.com/conda-forge/rod-feedstock/pull/8#issuecomment-2120343587)).

It looks to me that this is an upstream issue. If you agree, let's close this issue and open a corresponding issue in the [gitpython-feedstock issue tracker](https://github.com/conda-forge/gitpython-feedstock/issues)?

**Comment by diegoferigo** [comment]
> It looks to me that this is an upstream issue. If you agree, let's close this issue and open a corresponding issue in the [gitpython-feedstock issue tracker](https://github.com/conda-forge/gitpython-feedstock/issues)?

I had a discussion with the maintainers of `gitpython` in https://github.com/conda-forge/gitpython-feedstock/issues/80, feel free to draw your conclusions. I still believe that lifting the need to install `git` is something desirable, but at this point if this is something you want to achieve for your package, it is your choice.

Feel free to close this issue if you prefer keeping things as they are.

**Comment by stephane-caron** [comment]
Hmm interesting, I see that there are pros and cons on both sides of that decision. Thanks for flowing the info :+1: 

So far the working assumptions in robot-descriptions are the same as gitpython (i.e. we don't have specific additional assumptions that push for overriding the upstream decision), so I'd say let's keep matching upstream for now. The decision is now documented here and we can come back to it later if this evolves.
